CREATE TABLE SubCategory (
    `Id` VARCHAR(22) CHARACTER SET utf8,
    `SubCategory` VARCHAR(20) CHARACTER SET utf8
);
INSERT INTO SubCategory VALUES ('totem','Totem');
INSERT INTO SubCategory VALUES ('animals','Animal');
INSERT INTO SubCategory VALUES ('oregatherer_helmet','Miner Cap');
INSERT INTO SubCategory VALUES ('fibergatherer_shoes','Harvester Workboots');
INSERT INTO SubCategory VALUES ('chest','Chest');
INSERT INTO SubCategory VALUES ('bag','Bag');
INSERT INTO SubCategory VALUES ('plate_shoes','Plate Shoes');
INSERT INTO SubCategory VALUES ('offhand_artefact','Offhand');
INSERT INTO SubCategory VALUES ('hide','Hide');
INSERT INTO SubCategory VALUES ('woodgatherer_shoes','Lumberjack Workboots');
INSERT INTO SubCategory VALUES ('rockgatherer_armor','Quarrier Garb');
INSERT INTO SubCategory VALUES ('potion','Potion');
INSERT INTO SubCategory VALUES ('table','Table');
INSERT INTO SubCategory VALUES ('soul','Soul');
INSERT INTO SubCategory VALUES ('leather','Leather');
INSERT INTO SubCategory VALUES ('holystaff','Holy Staff');
INSERT INTO SubCategory VALUES ('mission','Mission Item');
INSERT INTO SubCategory VALUES ('rockgatherer_shoes','Quarrier Workboots');
INSERT INTO SubCategory VALUES ('planks','Planks');
INSERT INTO SubCategory VALUES ('froststaff','Frost Staff');
INSERT INTO SubCategory VALUES ('leather_shoes','Leather Shoes');
INSERT INTO SubCategory VALUES ('skinningknife','Skinning Knife');
INSERT INTO SubCategory VALUES ('armor_artefact','Armor');
INSERT INTO SubCategory VALUES ('cloth_armor','Cloth Armor');
INSERT INTO SubCategory VALUES ('rockgatherer_helmet','Quarrier Cap');
INSERT INTO SubCategory VALUES ('leather_armor','Leather Armor');
INSERT INTO SubCategory VALUES ('magic_artefact','Magic');
INSERT INTO SubCategory VALUES ('melee_artefact','Melee');
INSERT INTO SubCategory VALUES ('woodgatherer_backpack','Lumberjack Backpack');
INSERT INTO SubCategory VALUES ('woodgatherer_helmet','Lumberjack Cap');
INSERT INTO SubCategory VALUES ('fibergatherer_helmet','Harvester Cap');
INSERT INTO SubCategory VALUES ('hidegatherer_backpack','Skinner Backpack');
INSERT INTO SubCategory VALUES ('axe','Axe');
INSERT INTO SubCategory VALUES ('crossbow','Crossbow');
INSERT INTO SubCategory VALUES ('mercenarytrophy','Mercenary Trophy');
INSERT INTO SubCategory VALUES ('banner','Banner');
INSERT INTO SubCategory VALUES ('rare_mount','Rare Mount');
INSERT INTO SubCategory VALUES ('arcanestaff','Arcane Staff');
INSERT INTO SubCategory VALUES ('heretic_furniture','Heretic');
INSERT INTO SubCategory VALUES ('rune','Rune');
INSERT INTO SubCategory VALUES ('metalbar','Metal Bar');
INSERT INTO SubCategory VALUES ('pickaxe','Pickaxe');
INSERT INTO SubCategory VALUES ('horn','Horn');
INSERT INTO SubCategory VALUES ('oregatherer_armor','Miner Garb');
INSERT INTO SubCategory VALUES ('cooked','Cooked');
INSERT INTO SubCategory VALUES ('quarterstaff','Quarterstaff');
INSERT INTO SubCategory VALUES ('hidegatherer_armor','Skinner Garb');
INSERT INTO SubCategory VALUES ('plate_armor','Plate Armor');
INSERT INTO SubCategory VALUES ('bow','Bow');
INSERT INTO SubCategory VALUES ('keeper_furniture','Keeper');
INSERT INTO SubCategory VALUES ('hammer','Hammer');
INSERT INTO SubCategory VALUES ('hidegatherer_helmet','Skinner Cap');
INSERT INTO SubCategory VALUES ('relic','Relic');
INSERT INTO SubCategory VALUES ('plate_helmet','Plate Helmet');
INSERT INTO SubCategory VALUES ('cape','Cape');
INSERT INTO SubCategory VALUES ('ranged_artefact','Ranged');
INSERT INTO SubCategory VALUES ('stoneblock','Stone Block');
INSERT INTO SubCategory VALUES ('cursestaff','Cursed Staff');
INSERT INTO SubCategory VALUES ('firestaff','Fire Staff');
INSERT INTO SubCategory VALUES ('hidetrophy','Hide Trophy');
INSERT INTO SubCategory VALUES ('shield','Shield');
INSERT INTO SubCategory VALUES ('repairkit','Repair Kit');
INSERT INTO SubCategory VALUES ('torch','Torch');
INSERT INTO SubCategory VALUES ('stonehammer','Stone Hammer');
INSERT INTO SubCategory VALUES ('cloth','Cloth');
INSERT INTO SubCategory VALUES ('cloth_shoes','Cloth Shoes');
INSERT INTO SubCategory VALUES ('essence','Essence');
INSERT INTO SubCategory VALUES ('sickle','Sickle');
INSERT INTO SubCategory VALUES ('armoredhorse','Armored Horse');
INSERT INTO SubCategory VALUES ('ore','Ore');
INSERT INTO SubCategory VALUES ('book','Book');
INSERT INTO SubCategory VALUES ('sword','Sword');
INSERT INTO SubCategory VALUES ('leather_helmet','Leather Helmet');
INSERT INTO SubCategory VALUES ('flag','Flag');
INSERT INTO SubCategory VALUES ('naturestaff','Nature Staff');
INSERT INTO SubCategory VALUES ('rockgatherer_backpack','Quarrier Backpack');
INSERT INTO SubCategory VALUES ('cloth_helmet','Cloth Helmet');
INSERT INTO SubCategory VALUES ('fibergatherer_armor','Harvester Garb');
INSERT INTO SubCategory VALUES ('vanity','Vanity');
INSERT INTO SubCategory VALUES ('farming','Farming');
INSERT INTO SubCategory VALUES ('bed','Bed');
INSERT INTO SubCategory VALUES ('other','Other');
INSERT INTO SubCategory VALUES ('token','Tokens');
INSERT INTO SubCategory VALUES ('wood','Wood');
INSERT INTO SubCategory VALUES ('rock','Rock');
INSERT INTO SubCategory VALUES ('fibergatherer_backpack','Harvester Backpack');
INSERT INTO SubCategory VALUES ('ridinghorse','Riding Horse');
INSERT INTO SubCategory VALUES ('woodaxe','Wood Axe');
INSERT INTO SubCategory VALUES ('unique','Unique');
INSERT INTO SubCategory VALUES ('trash','Trash');
INSERT INTO SubCategory VALUES ('woodgatherer_armor','Lumberjack Garb');
INSERT INTO SubCategory VALUES ('fiber','Fiber');
INSERT INTO SubCategory VALUES ('orb','Orb');
INSERT INTO SubCategory VALUES ('seed','Seed');
INSERT INTO SubCategory VALUES ('generaltrophy','General Trophy');
INSERT INTO SubCategory VALUES ('journal','Journals');
INSERT INTO SubCategory VALUES ('ox','Ox');
INSERT INTO SubCategory VALUES ('morgana_furniture','Morgana');
INSERT INTO SubCategory VALUES ('oregatherer_shoes','Miner Workboots');
INSERT INTO SubCategory VALUES ('hidegatherer_shoes','Skinner Workboots');
INSERT INTO SubCategory VALUES ('dagger','Dagger');
INSERT INTO SubCategory VALUES ('demolitionhammer','Demolition Hammer');
INSERT INTO SubCategory VALUES ('mace','Mace');
INSERT INTO SubCategory VALUES ('oregatherer_backpack','Miner Backpack');
INSERT INTO SubCategory VALUES ('spear','Spear');
